version: "3"

services:
  nginx:
    build: ./front/
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - profile_pictures:/media
      - ./.logs/nginx:/var/log/nginx
    depends_on:
      - django

  django:
    build: ./back/
    container_name: django
    ports:
      - 8000:8000
    volumes:
      - profile_pictures:/core/media
    env_file:
      - .env
    depends_on:
      - db

  db:
    build: ./db/
    container_name: db
    expose:
      - 5432
    volumes:
      - ddbb:/var/lib/postgresql/data
      - ./.logs/db:/log
    command: -c 'config_file=/etc/postgresql/postgresql.conf'
    env_file:
      - .env

  redis:
    image: "redis:7.2.3-alpine"
    container_name: "redis"
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
      
# Monitoring
  prometheus:
    # TODO secure with user password
    image: prom/prometheus:v2.49.1
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/alert_rules.yml:/etc/prometheus/alert_rules.yml
      - prom_data:/prometheus

  alertmanager:
    # TODO secure with user password
    image: prom/alertmanager:v0.21.0
    container_name: alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./prometheus/alertmanager.yml:/etc/alertmanager/alertmanager.yml

  elasticsearch:
    # TODO secure with user password
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.1
    container_name: elasticsearch
    environment:
      ES_JAVA_OPTS: -Xms512m -Xmx512m
    #mem_limit: 1g #in case we think is necesary to Mac of 42
    #cpus: '0.5'
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
      - ./elk-config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

  logstash:
    image: docker.elastic.co/logstash/logstash:8.12.1
    container_name: logstash
    ports:
      - "5000:5000"
      - "5054:5054"
    ## TODO ssl enable to secure logstah
    volumes:
      - ./elk-config/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./.logs:/var/log/services
    depends_on:
      - elasticsearch

  kibana:
    # TODO secure with user password
    image: docker.elastic.co/kibana/kibana:8.12.1
    container_name: kibana
    volumes:
      - ./elk-config/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
# Django    dashboard    17658
# Postgres  dashboard  9628
# Nginx     dashboard     12708
  grafana:
    image: grafana/grafana:10.3.1
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - graf_data:/var/lib/grafana
    environment:
    #TODO Secure this credentials, for now development doesnt matter
      - GF_SECURITY_ADMIN_USER=test-user
      - GF_SECURITY_ADMIN_PASSWORD=test
    depends_on:
      - prometheus

  # Oficial exporters https://prometheus.io/docs/instrumenting/exporters/
  postgres_exporter:
    image: quay.io/prometheuscommunity/postgres-exporter:v0.15.0
    container_name: postgres_exporter
    expose:
      - 9187
    environment:
      - DATA_SOURCE_NAME=postgresql://postgres:postgres@db:5432/postgres?sslmode=disable
    depends_on:
      - prometheus
      - db

  nginx_exporter:
    image: nginx/nginx-prometheus-exporter:1.1.0
    container_name: nginx_exporter
    expose:
      - 9113
    command:
      - --nginx.scrape-uri=http://nginx:80/nginx_status
    depends_on:
      - prometheus
      - nginx

volumes:
  ddbb:
  profile_pictures:
  prom_data:
  graf_data:
  elasticsearch_data:
