version: "3"

services:
  nginx:
    build: ./front/
    container_name: nginx
    ports:
      - 80:80
    depends_on:
      - django

  django:
    build: ./back/
    container_name: django
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db

  db:
    build: ./db/
    container_name: db
    volumes:
      - ddbb:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  ddbb: