global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
            - "alertmanager:9093"
rule_files:
  - "./alert_rules.yml"
scrape_configs:
  - job_name: 'postgres'
    static_configs:
      - targets:
        - postgres_exporter:9187
  - job_name: 'nginx'
    static_configs:
      - targets:
        - nginx_exporter:9113
  - job_name: 'django'
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets:
        - django:8000
