global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
scrape_configs:
  #- job_name: prometheus
  #  scrape_interval: 15s
  #  scrape_timeout: 10s
  #  scheme: http
  #  static_configs:
  #  - targets:
  #    - localhost:9090

  - job_name: 'postgres'
    static_configs:
      - targets:
        - postgres_exporter:9187
  - job_name: 'nginx'
    static_configs:
      - targets:
        - nginx_exporter:9113