FROM postgres:16-bullseye

# In case we need to add any special config, if not run postgres image directly in compose

#COPY ./conf/override.conf /etc/systemd/system/postgresql.service.d/override.conf

#RUN sed -i 's/\*/django/g' /var/lib/postgresql/data/postgresql.conf